// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateOrder implements CreateOrder operation.
//
// Создание заказа.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderByUUID implements OrderByUUID operation.
//
// Возвращает информацию о заказе.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) OrderByUUID(ctx context.Context, params OrderByUUIDParams) (r OrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderCancel implements Order cancel operation.
//
// Отменить заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) OrderCancel(ctx context.Context, params OrderCancelParams) (r OrderCancelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderPay implements OrderPay operation.
//
// Оплата заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (r OrderPayRes, _ error) {
	return r, ht.ErrNotImplemented
}
